image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      (cd lib && git clone https://github.com/YtGz/monad-supply.git)
      cabal update
      cabal install hpack
      (cd lib/monad-supply && hpack)
      cabal build

vscode:
  extensions:
    - haskell.haskell